# vim: set ts=2 sw=2 et:

version: '3.4'

services:
  wordpress:
    build:
      context: .
      dockerfile: ./compose/local/wordpress/Dockerfile
      target: local
    image: img_demo_wordpress
    container_name: ctr_demo_wordpress
    env_file:
      - ./compose/local/.env
    expose:
      - '9000'
    volumes:
      - ./src:/var/www/html
      - ./compose/local/wordpress/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    networks:
      - app-tier
    restart: unless-stopped
    depends_on:
      - db
      - redis
    entrypoint: ["/entrypoint.sh"]
    command: ["php-fpm"]

  nginx:
    image: nginx:latest
    container_name: ctr_demo_nginx
    env_file:
      - ./compose/local/.env
    ports:
      - '80:80'
    networks:
      - app-tier
    volumes:
      - ./src:/var/www/html
      - ./compose/local/nginx/wordpress-fpm.conf:/etc/nginx/templates/default.conf.template:ro
      - ./compose/local/nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  redis:
    image: redis:5.0-alpine
    container_name: ctr_demo_redis
    expose:
      - '6379'
    networks:
      - app-tier

   db:
      container_name: ctr_demo_db
      image: mysql:5.7
      restart: on-failure
      env_file:
        - ./compose/local/.env
      expose:
        - '3306'
      volumes:
        - demo_db:/var/lib/mysql
        - ./compose/local/mysql/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf:ro

networks:
  app-tier:
    driver: bridge

volumes:
    demo_db: {}
